### PR TITLE
Use standard if/else braces

### PR DESCRIPTION
**Pull request by lachlanjc**

### CODE REVIEW

**Comment by MatthewStanciu** [comment]
This looks dumb

**Comment by MatthewStanciu** [comment]
Sorry what I meant is I don’t like using braces if it’s just one line and I don’t have to because it looks ugly

**Comment by lachlanjc** [comment]
It’s literally the same number of lines & I’ve never seen this combination of syntax anywhere before & it looks broken. Also I gave you rich quotes. So.

**Comment by MatthewStanciu** [comment]
Thanks for the rich quotes, just added those. I think this is a case where everyone else is wrong and I’m right, just like how I’m right about putting punctuation outside of quotes in a sentence where it makes sense

**Comment by MatthewStanciu** [comment]
It may look broken and “incorrect” to everyone else but it actually makes the most sense

**Comment by MatthewStanciu** [comment]
conclusion: i’m smart

**Pull request closed without merging**
